README.md
app/build.gradle
build.gradle
gradle/wrapper/gradle-wrapper.properties

- Upgraded to AGP 4.2.0-alpha14
- Upgraded to build tools 30.0.2
- Updated README

Upgraded to Android Gradle Plugin 4.2.0-alpha14

---

README.md
build.gradle
gradle/wrapper/gradle-wrapper.properties

- Updated AGP to 4.2.0-alpha15
- Updated Gradle wrapper to 6.7 release
- Updated README
Closes #18

Upgraded to Android Gradle Plugin 4.2.0-alpha15

---

app/src/main/java/com/guru/composecookbook/ui/demoui/gmail/GmailDrawer.kt
app/src/main/java/com/guru/composecookbook/ui/demoui/gmail/GmailHome.kt

Added side bar drawer UI and drawer open on navigation icons.

Added side drawer for the Gmail UI

---

app/build.gradle
app/src/main/java/com/guru/composecookbook/ui/demoui/gmail/AnimatingFabContent.kt
app/src/main/java/com/guru/composecookbook/ui/demoui/gmail/GmailDrawer.kt
app/src/main/java/com/guru/composecookbook/ui/demoui/gmail/GmailHome.kt
build.gradle

Since, alpha version of navigation has been out. Let's integrate some of our screen with it.

update dependencies & added alpha of compose navigation & animated fab

---

app/build.gradle
app/src/main/java/com/guru/composecookbook/ui/constraintlayout/ConstrintLayoutDemos.kt
app/src/main/java/com/guru/composecookbook/ui/demoui/DemoUIHostActivity.kt
app/src/main/java/com/guru/composecookbook/ui/demoui/gmail/GmailHome.kt
app/src/main/java/com/guru/composecookbook/ui/demoui/gmail/SearchLayout.kt
app/src/main/java/com/guru/composecookbook/ui/demoui/gmail/create/CreateMessageBody.kt
app/src/main/java/com/guru/composecookbook/ui/demoui/gmail/create/CreateMessageScreen.kt
app/src/main/java/com/guru/composecookbook/ui/demoui/gmail/data/SampleData.kt
app/src/main/java/com/guru/composecookbook/ui/demoui/gmail/details/MessageDetailBody.kt
app/src/main/java/com/guru/composecookbook/ui/demoui/gmail/details/MessageDetailScreen.kt
app/src/main/java/com/guru/composecookbook/ui/demoui/gmail/home/AnimatingFabContent.kt
app/src/main/java/com/guru/composecookbook/ui/demoui/gmail/home/GmailDrawer.kt
app/src/main/java/com/guru/composecookbook/ui/demoui/gmail/home/GmailHome.kt
app/src/main/java/com/guru/composecookbook/ui/demoui/gmail/home/GmailListItem.kt
app/src/main/java/com/guru/composecookbook/ui/demoui/gmail/home/SearchLayout.kt

Gmail like search button & expand and collapse. It's really laggy right now, maybe due to experimental APIs, and also refactoring gmail items to row/columns may give some performance.

gmail search layout & basic collapse/expand on scroll

---

app/src/main/java/com/guru/composecookbook/ui/demoui/gmail/home/GmailHome.kt
app/src/main/java/com/guru/composecookbook/ui/demoui/gmail/home/SearchLayout.kt

User email dialog

---

app/src/main/java/com/guru/composecookbook/ui/advancelists/LoadingShimmerList.kt
app/src/main/java/com/guru/composecookbook/ui/components/HeartButton.kt
gradle.properties

Add heart animation composable for toggling a favorite.

Heart animation and rounded corner loading list.

---

app/src/main/java/com/guru/composecookbook/ui/advancelists/LoadingShimmerList.kt
app/src/main/java/com/guru/composecookbook/ui/components/HeartButton.kt
app/src/main/java/com/guru/composecookbook/ui/components/HorizontalDottedProgressBar.kt
gradle.properties

Add a 5 dot horizontal progress bar

Horizontal dotted progress bar

---

app/build.gradle
app/src/androidTest/java/com/guru/composecookbook/BottomNavigationBarTests.kt
app/src/androidTest/java/com/guru/composecookbook/ui/home/HomeScreenTest.kt

- Fixed new test packages names for compose alpha-08
- Fixed unit tests compilation error caused by meta files `META-INF/AL2.0` and `META-INF/LGPL2.1`
- Fixed Junit5 configuration (Added Engine and correct Gradle conf)

Fixed compilation error for unit and instrumentation tests (#34)

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/guru/composecookbook/theme/SystemUI.kt
app/src/main/java/com/guru/composecookbook/ui/Animations/AnimationScreen.kt
app/src/main/java/com/guru/composecookbook/ui/advancelists/AdvanceListsActivity.kt
app/src/main/java/com/guru/composecookbook/ui/advancelists/AnimatedLists.kt
app/src/main/java/com/guru/composecookbook/ui/androidviews/AndroidViews.kt
app/src/main/java/com/guru/composecookbook/ui/carousel/CarouselLayout.kt
app/src/main/java/com/guru/composecookbook/ui/carousel/Pager.kt
app/src/main/java/com/guru/composecookbook/ui/constraintlayout/ConstrintLayoutDemos.kt
app/src/main/java/com/guru/composecookbook/ui/cryptoappmvvm/ui/home/CryptoHomeScreen.kt
app/src/main/java/com/guru/composecookbook/ui/datingapp/components/DraggableCard.kt
app/src/main/java/com/guru/composecookbook/ui/demoui/DemoUIList.kt
app/src/main/java/com/guru/composecookbook/ui/demoui/gmail/create/CreateMessageBody.kt
app/src/main/java/com/guru/composecookbook/ui/demoui/gmail/home/SearchLayout.kt
app/src/main/java/com/guru/composecookbook/ui/demoui/spotify/SpotifyComponents.kt
app/src/main/java/com/guru/composecookbook/ui/demoui/tiktok/TikTokPlayer.kt
app/src/main/java/com/guru/composecookbook/ui/demoui/tiktok/home/HomeScreen.kt
app/src/main/java/com/guru/composecookbook/ui/dynamic/DynamicUIActivity.kt
app/src/main/java/com/guru/composecookbook/ui/dynamic/Modifiers.kt
app/src/main/java/com/guru/composecookbook/ui/home/HomeScreen.kt
app/src/main/java/com/guru/composecookbook/ui/learnwidgets/Layouts.kt
app/src/main/java/com/guru/composecookbook/ui/learnwidgets/Snackbars.kt
app/src/main/java/com/guru/composecookbook/ui/moviesappmvi/ui/home/MoviePagerItem.kt
app/src/main/java/com/guru/composecookbook/ui/moviesappmvi/ui/home/MoviesHomeScreen.kt
app/src/main/java/com/guru/composecookbook/ui/profile/ProfileScreen.kt
app/src/main/java/com/guru/composecookbook/ui/pullrefreshdemos/PullRefreshList.kt
app/src/main/java/com/guru/composecookbook/ui/utils/CommomComponents.kt
app/src/main/java/com/guru/composecookbook/ui/utils/ModifierExtentions.kt

- Replaced Deprecated APIs with recommended ones
- Applied Compose Code Style for certain Compose functions
- Fixed 5 Android Linter Errors
- Fixed 14 Linter Warnings
Before : 
After :

Fixed Deprecated APIs after Compose version migrations (#36)

---

README.md
app/build.gradle
app/src/androidTest/java/com/guru/composecookbook/BottomNavigationBarTests.kt
app/src/main/java/com/guru/composecookbook/MainActivity.kt
app/src/main/java/com/guru/composecookbook/ui/advancelists/LoadingShimmerList.kt
app/src/main/java/com/guru/composecookbook/ui/cryptoappmvvm/ui/detail/CryptoDetailScreen.kt
app/src/main/java/com/guru/composecookbook/ui/cryptoappmvvm/ui/home/CryptoHomeScreen.kt
app/src/main/java/com/guru/composecookbook/ui/datingapp/DatingChatScreen.kt
app/src/main/java/com/guru/composecookbook/ui/datingapp/DatingHomeScreen.kt
app/src/main/java/com/guru/composecookbook/ui/datingapp/components/DraggableCard.kt
app/src/main/java/com/guru/composecookbook/ui/demoui/gmail/home/GmailHome.kt
app/src/main/java/com/guru/composecookbook/ui/demoui/instagram/InstagramStories.kt
app/src/main/java/com/guru/composecookbook/ui/demoui/spotify/SpotifyHome.kt
app/src/main/java/com/guru/composecookbook/ui/demoui/spotify/SpotifySearchScreen.kt
app/src/main/java/com/guru/composecookbook/ui/demoui/tiktok/discover/Discover.kt
app/src/main/java/com/guru/composecookbook/ui/demoui/youtube/YoutubeHome.kt
app/src/main/java/com/guru/composecookbook/ui/dialogs/DialogsActivity.kt
app/src/main/java/com/guru/composecookbook/ui/dynamic/Modifiers.kt
app/src/main/java/com/guru/composecookbook/ui/lists/ListViewActivity.kt
app/src/main/java/com/guru/composecookbook/ui/moviesappmvi/ui/MoviesLaneItem.kt
app/src/main/java/com/guru/composecookbook/ui/moviesappmvi/ui/details/MovieDetailActivity.kt
app/src/main/java/com/guru/composecookbook/ui/moviesappmvi/ui/home/WatchlistScreen.kt
app/src/main/java/com/guru/composecookbook/ui/utils/ModifierExtentions.kt
build.gradle
gradle/wrapper/gradle-wrapper.properties

- Upgraded to Compose Alpha-09
- Fixed compilation errors
- Fixed broken unit tests
- Upgraded to AGP 7.0.0-alpha03
- Replaced deprecated APIs

Upgraded to Jetpack Compose Alpha-09 (#38)

---

app/src/main/java/com/guru/composecookbook/ui/advancelists/AnimatedLists.kt
app/src/main/java/com/guru/composecookbook/ui/advancelists/LoadingShimmerList.kt
app/src/main/java/com/guru/composecookbook/ui/advancelists/SwipeableLists.kt
app/src/main/java/com/guru/composecookbook/ui/cryptoappmvvm/ui/home/CryptoHomeScreen.kt
app/src/main/java/com/guru/composecookbook/ui/cryptoappmvvm/ui/home/components/MyWalletCard.kt
app/src/main/java/com/guru/composecookbook/ui/demoui/DemoUIList.kt
app/src/main/java/com/guru/composecookbook/ui/demoui/instagram/InstagramHome.kt
app/src/main/java/com/guru/composecookbook/ui/demoui/spotify/SpotifyComponents.kt
app/src/main/java/com/guru/composecookbook/ui/demoui/twitter/TwitterHome.kt
app/src/main/java/com/guru/composecookbook/ui/home/HomeScreen.kt
app/src/main/java/com/guru/composecookbook/ui/lists/ListViewActivity.kt
app/src/main/java/com/guru/composecookbook/ui/moviesappmvi/ui/home/WatchlistScreen.kt
app/src/main/java/com/guru/composecookbook/ui/pullrefreshdemos/PullRefreshList.kt
build.gradle
gradle.properties

- Replaced `LazyColumnFor`
- Replaced `LazyColumnForIndexed`
- Replaced `FloatingActionButtonConstants`
- Added deprecation warning at compile time for Gradle

Replaced deprecated Compose APIs (#40)

---

app/build.gradle
app/src/main/java/com/guru/composecookbook/ui/demoapps/cryptoappmvvm/data/api/CryptoApi.kt
app/src/main/java/com/guru/composecookbook/ui/demoapps/cryptoappmvvm/data/repository/CryptoRepository.kt
app/src/main/java/com/guru/composecookbook/ui/demoapps/cryptoappmvvm/data/repository/CryptoRepositoryImpl.kt
app/src/main/java/com/guru/composecookbook/ui/demoapps/cryptoappmvvm/ui/home/CryptoHomeActivity.kt
app/src/main/java/com/guru/composecookbook/ui/demoapps/cryptoappmvvm/ui/home/CryptoHomeScreen.kt
app/src/main/java/com/guru/composecookbook/ui/demoapps/cryptoappmvvm/ui/home/CryptoHomeViewModel.kt
app/src/main/java/com/guru/composecookbook/ui/templates/Charts.kt
app/src/main/java/com/guru/composecookbook/ui/utils/PageNumSource.kt
build.gradle

1.update version  of some libraries 2.crypto list replace with paging-compose 3.bugfix index outbound

Mainly change:  crypto list replace with paging-compose

---

app/build.gradle.kts
app/src/androidTest/java/com/guru/composecookbook/ui/flings/FlingListActivityTest.kt
app/src/androidTest/java/com/guru/composecookbook/ui/flings/FlingSettingsPageTest.kt
app/src/main/AndroidManifest.xml
app/src/main/java/com/guru/composecookbook/data/DemoDataProvider.kt
app/src/main/java/com/guru/composecookbook/ui/home/HomeScreen.kt
app/src/main/java/com/guru/composecookbook/ui/home/HomeScreenItems.kt
app/src/main/java/com/guru/composecookbook/ui/home/customfling/FlingListActivity.kt
app/src/main/java/com/guru/composecookbook/ui/home/customfling/FlingListSettingsActivity.kt
app/src/main/java/com/guru/composecookbook/ui/home/customfling/FlingListViewTypes.kt
app/src/main/java/com/guru/composecookbook/ui/home/customfling/FlingStateStore.kt
app/src/main/java/com/guru/composecookbook/ui/home/customfling/ListItemDivider.kt
app/src/main/java/com/guru/composecookbook/ui/home/customfling/SettingsPage.kt
app/src/main/java/com/guru/composecookbook/ui/home/customfling/VerticalFlingerList.kt
app/src/main/java/com/guru/composecookbook/ui/home/customfling/VerticalFlingerListItem.kt
app/src/main/java/com/guru/composecookbook/ui/utils/FloatUtil.kt
app/src/main/res/values/strings.xml
buildSrc/src/main/kotlin/com.guru.composecookbook.build/Dependencies.kt

Completed integrating Flinger library as mentioned in - https://github.com/Gurupreet/ComposeCookBook/issues/64#issue-900271321
Also added the UI tests to improve the code coverage.

Flinger Library Implementation 

---

.gitignore
app/src/androidTest/java/com/guru/composecookbook/BottomNavigationBarTests.kt
app/src/main/java/com/guru/composecookbook/MainActivity.kt

** This has some extra addon `testTags` in the MainActivity.kt file.

BottomNavigationBarTests.kt test fixes

---

README.md

added GIF for flinger in the Readme.md file

flinger gif added

---

app/src/androidTest/java/com/guru/composecookbook/ui/home/home_screen_options/VerticalListTest.kt
app/src/main/java/com/guru/composecookbook/ui/home/HomeScreen.kt
app/src/main/java/com/guru/composecookbook/ui/home/lists/VerticalListItem.kt

Added VerticalListTest.kt in the UI test - for UI Vertical list option to improve code coverage.

Added UI test for home screen options.

---

app/src/main/java/com/guru/composecookbook/ui/home/advancelists/SwipeableLists.kt

make swipeable lists stop in the middle so user can choose from Icons

make swipeable lists stop in middle so user can choose from Icons

---

app/src/androidTest/java/com/guru/composecookbook/BottomNavigationBarTests.kt
buildSrc/src/main/kotlin/com/guru/composecookbook/build/dependencies/GroupedDependencies.kt

Fixed instrumentation tests

---

app/src/androidTest/java/com/guru/composecookbook/BottomNavigationBarTests.kt
app/src/androidTest/java/com/guru/composecookbook/ui/flings/FlingListActivityTest.kt
app/src/androidTest/java/com/guru/composecookbook/ui/flings/FlingSettingsPageTest.kt
app/src/androidTest/java/com/guru/composecookbook/ui/home/HomeScreenTest.kt
app/src/androidTest/java/com/guru/composecookbook/ui/home/home_screen_options/HorizontalListTest.kt
app/src/main/java/com/guru/composecookbook/MainActivity.kt
app/src/main/java/com/guru/composecookbook/ui/animation/AnimationScreen.kt
app/src/main/java/com/guru/composecookbook/ui/demoapps/DemoUIList.kt
app/src/main/java/com/guru/composecookbook/ui/home/HomeScreen.kt
app/src/main/java/com/guru/composecookbook/ui/home/customfling/FlingListActivity.kt
app/src/main/java/com/guru/composecookbook/ui/home/customfling/FlingListSettingsActivity.kt
app/src/main/java/com/guru/composecookbook/ui/home/customfling/SettingsPage.kt
app/src/main/java/com/guru/composecookbook/ui/home/customfling/VerticalFlingerList.kt
app/src/main/java/com/guru/composecookbook/ui/home/lists/HorizontalListItem.kt
app/src/main/java/com/guru/composecookbook/ui/home/lists/VerticalListItem.kt
app/src/main/java/com/guru/composecookbook/ui/learnwidgets/WidgetScreen.kt
app/src/main/java/com/guru/composecookbook/ui/templates/TemplateScreen.kt
app/src/main/java/com/guru/composecookbook/ui/utils/TestTags.kt
build.gradle.kts
buildSrc/build.gradle.kts

- **HorizontalListTest.kt** added.
- Created **TestTags.kt** class to put in all testTags for improving code readability.
- Gradle version upgraded to **7.1.0-alpha02**

UI test added for HorizontalList 

---

app/src/androidTest/java/com/guru/composecookbook/ui/home/home_screen_options/GridListTest.kt
app/src/androidTest/java/com/guru/composecookbook/ui/home/home_screen_options/flings/FlingListActivityTest.kt
app/src/androidTest/java/com/guru/composecookbook/ui/home/home_screen_options/flings/FlingSettingsPageTest.kt
app/src/main/java/com/guru/composecookbook/ui/home/lists/GridListItem.kt
app/src/main/java/com/guru/composecookbook/ui/home/lists/ListViewActivity.kt

+ Added GridListTest.kt test
+ Added testTag in GridListItem.kt

GridList UI test added

---

app/src/androidTest/java/com/guru/composecookbook/ui/home/home_screen_options/LayoutsTest.kt
app/src/main/java/com/guru/composecookbook/ui/learnwidgets/Layouts.kt
app/src/main/java/com/guru/composecookbook/ui/utils/TestTags.kt

+ Added LayoutsTest.kt test
+ Added testTag in Layouts.kt.kt
+ updated TestTags.kt with the tags for Layouts.kt screen.

Home Layouts screen test added.

---

gradle/wrapper/gradle-wrapper.properties

Updated Gradle Wrapper to 7.1

---

demos/moviesapp/app/src/main/java/com/guru/composecookbook/moviesapp/ui/home/MoviesHomeActivity.kt
demos/moviesapp/app/src/main/java/com/guru/composecookbook/moviesapp/ui/home/components/MoviePagerItem.kt
demos/moviesapp/app/src/main/java/com/guru/composecookbook/moviesapp/ui/home/components/MoviesPager.kt
demos/moviesapp/app/src/main/java/com/guru/composecookbook/moviesapp/ui/trending/components/MovieTrendingScreen.kt
demos/moviesapp/app/src/main/java/com/guru/composecookbook/moviesapp/ui/watch/components/WatchlistScreen.kt

Please first review and merge #83
Result:
https://user-images.githubusercontent.com/9992216/122648471-07069380-d15c-11eb-9a04-094caa60e87e.mp4

Make movie demo app view pager items animation offset based

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/guru/composecookbook/MainActivity.kt
app/src/main/java/com/guru/composecookbook/ui/animation/AnimationScreen.kt
app/src/main/java/com/guru/composecookbook/ui/animation/TransitionsAnimations.kt
app/src/main/java/com/guru/composecookbook/ui/home/constraintlayout/ConstraintLayoutDemos.kt
app/src/main/java/com/guru/composecookbook/ui/home/customfling/FlingListSettingsActivity.kt
app/src/main/java/com/guru/composecookbook/ui/home/lists/ListViewActivity.kt
app/src/main/java/com/guru/composecookbook/ui/home/tabslayout/TabLayout.kt
app/src/main/java/com/guru/composecookbook/ui/learnwidgets/SwipeButton.kt
components/fab/src/main/java/com/guru/composecookbook/fab/AnimatingFabContent.kt
data/src/main/java/com/guru/composecookbook/data/DemoDataProvider.kt
demos/tiktok/src/main/java/com/guru/composecookbook/tiktok/components/home/TikTokPlayer.kt

- Add label for animation
- refactor file, package directive, and remove unnecessary tag and parentheses
- change unmodified variable to immutable

refactor to tidy up things

---

README.md
app/src/test/java/com/guru/composecookbook/ui/home/HomeScreenItemsTest.kt
build.gradle.kts
buildSrc/src/main/kotlin/com/guru/composecookbook/build/dependencies/Versions.kt

the readme badge is updated too

update compose to rc02 and gradle to alpha03

---

app/src/main/java/com/guru/composecookbook/ui/demoapps/DemoUIList.kt
app/src/main/java/com/guru/composecookbook/ui/home/advancelists/AnimatedLists.kt
buildSrc/src/main/kotlin/com/guru/composecookbook/build/dependencies/Dependencies.kt
buildSrc/src/main/kotlin/com/guru/composecookbook/build/dependencies/GroupedDependencies.kt
buildSrc/src/main/kotlin/com/guru/composecookbook/build/dependencies/Versions.kt
demos/moviesapp/app/src/main/java/com/guru/composecookbook/moviesapp/ui/home/MoviewsHomeViewModel.kt
demos/moviesapp/app/src/main/java/com/guru/composecookbook/moviesapp/ui/home/components/MoviePagerItem.kt
demos/moviesapp/app/src/main/java/com/guru/composecookbook/moviesapp/ui/trending/components/MoviesLaneItem.kt
demos/moviesapp/app/src/main/java/com/guru/composecookbook/moviesapp/ui/watch/components/MovieWatchlistItem.kt
demos/moviesapp/app/src/main/java/com/guru/composecookbook/moviesapp/ui/watch/components/WatchlistScreen.kt
demos/tiktok/src/main/java/com/guru/composecookbook/tiktok/components/discovers/MediaItem.kt
templates/login/src/main/java/com/guru/composecookbook/login/LoginScreen.kt
templates/profile/src/main/java/com/guru/composecookbook/profile/ProfileScreen.kt
templates/profile/src/main/java/com/guru/composecookbook/profile/TopScrollingContent.kt

*accompanist dependency still exist in case anyone working with it for this project

replace deprecated accompanist coil with coil compose

---

app/src/main/java/com/guru/composecookbook/ui/home/motionlayout/MotionLayoutDemo.kt

I think the JSON indentation is a bit weird, so i manually fix them to be more readable

optimize import and fix indentation

---

app/src/main/java/com/guru/composecookbook/ui/utils/Extentions.kt
build.gradle.kts
buildSrc/build.gradle.kts
demos/datingapp/src/main/java/com/guru/composecookbook/datingapp/DatingHomeViewModel.kt
demos/datingapp/src/main/java/com/guru/composecookbook/datingapp/components/home/DatingHomeScreen.kt
demos/datingapp/src/main/java/com/guru/composecookbook/datingapp/util/Extentions.kt
gradle/wrapper/gradle-wrapper.properties

There was a concurrent exception when we tried to set value for **`listEmpty.value`** .  So by changing the preparing albums data loved the problem form setting again persons list

DatingApp fixed minor bug 

---

.idea/kotlinScripting.xml
app/src/main/java/com/guru/composecookbook/ui/home/advancelists/AdvanceListsActivity.kt
components/carousel/src/main/java/com/guru/composecookbook/carousel/CarouselDot.kt
components/carousel/src/main/java/com/guru/composecookbook/carousel/CarouselLayout.kt
components/carousel/src/main/java/com/guru/composecookbook/carousel/PageData.kt
components/carousel/src/main/java/com/guru/composecookbook/carousel/Pager.kt
components/carousel/src/main/java/com/guru/composecookbook/carousel/PagerScope.kt
components/carousel/src/main/java/com/guru/composecookbook/carousel/PagerState.kt
components/carousel/src/main/java/com/guru/composecookbook/carousel/SelectionState.kt
demos/moviesapp/app/src/main/java/com/guru/composecookbook/moviesapp/ui/home/components/MoviesPager.kt
demos/tiktok/src/main/java/com/guru/composecookbook/tiktok/components/home/HomeScreen.kt
templates/onboarding/src/main/java/com/guru/composecookbook/onboarding/OnboardingScreen.kt

Sent user to the first item in the carousel when reached to the last item in the carousel
Also tried to separate related codes and make code more cleaner

Add circular behavior in the carousel component also make code more readable

---

app/src/main/java/com/guru/composecookbook/ui/home/timer/TimerDemo.kt
app/src/main/java/com/guru/composecookbook/ui/home/timer/TimerView.kt
app/src/main/java/com/guru/composecookbook/ui/home/timer/TimerViewModel.kt
app/src/main/java/com/guru/composecookbook/ui/templates/TemplateScreen.kt
app/src/main/java/com/guru/composecookbook/ui/templates/TemplatesActivity.kt

Created Timer Widget with following display format:
- HH:MM:SS
- HH:MM
- MM:SS
Added Demo Timer Template Screen With Countdown to EOD(11:59:59 PM)
| Dark Mode      | Light Mode |
| ----------- | ----------- |
|   ![Screenshot_1631985613](https://user-images.githubusercontent.com/7108762/133897532-cf1c53c3-1e29-49a5-8e70-fe10be9e86fe.png)   |    ![Screenshot_1631985621](https://user-images.githubusercontent.com/7108762/133897535-a537c6a9-2533-4b47-9761-8b316e6a7887.png)  |

Timer Widget template

---

app/src/main/java/com/guru/composecookbook/ui/home/clock/ClockDemo.kt
app/src/main/java/com/guru/composecookbook/ui/home/clock/ClockView.kt
app/src/main/java/com/guru/composecookbook/ui/home/clock/ClockViewModel.kt
app/src/main/java/com/guru/composecookbook/ui/templates/TemplateScreen.kt
app/src/main/java/com/guru/composecookbook/ui/templates/TemplatesActivity.kt

Added Clock View to template screen
https://user-images.githubusercontent.com/7108762/133931510-c756872c-6d11-4b28-a8ca-4abd80f73268.mp4
https://user-images.githubusercontent.com/7108762/133931532-a2f5189d-d812-4e0e-bf39-4fad1e965032.mp4

Added ClockView to template

---

app/src/main/java/com/guru/composecookbook/MainActivity.kt
app/src/main/java/com/guru/composecookbook/ui/templates/TemplatesActivity.kt
build.gradle.kts
buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/com/guru/composecookbook/build/dependencies/Dependencies.kt
buildSrc/src/main/kotlin/com/guru/composecookbook/build/dependencies/GroupedDependencies.kt
buildSrc/src/main/kotlin/com/guru/composecookbook/build/dependencies/Versions.kt
templates/login/src/main/java/com/guru/composecookbook/login/LoginScreen.kt
theme/src/main/java/com/guru/composecookbook/theme/MaterialTheme.kt
theme/src/main/java/com/guru/composecookbook/theme/helpers/TextFieldDefaultsMaterial.kt

@Gurupreet 
Here are few screenshots from android 12
@Gurupreet please let me know if I am missing something or doing wrong.

[Material You] Login template compatible to material you

---

app/src/main/java/com/guru/composecookbook/ui/home/constraintlayout/ConstraintLayoutDemos.kt
app/src/main/java/com/guru/composecookbook/ui/home/dialogs/BottomSheetLayouts.kt
app/src/main/java/com/guru/composecookbook/ui/home/dynamic/Modifiers.kt
app/src/main/java/com/guru/composecookbook/ui/home/motionlayout/MotionLayoutDemo.kt
app/src/main/java/com/guru/composecookbook/ui/learnwidgets/Layouts.kt
demos/gmail/src/main/java/com/guru/composecookbook/gmail/ui/home/GmailListItem.kt
demos/youtube/src/main/java/com/guru/composecookbook/youtube/components/YoutubeListItem.kt

@Gurupreet 
Material 3 improvements in these
- Modifiers
- Layouts
- ConstraintLayout
- MotionLayoutDemo
- BottomSheetLayout

More to Material you

---

app/src/main/java/com/guru/composecookbook/ui/home/advancelists/AdvanceListsActivity.kt
app/src/main/java/com/guru/composecookbook/ui/home/advancelists/AnimatedLists.kt
app/src/main/java/com/guru/composecookbook/ui/home/advancelists/Shimmer.kt
app/src/main/java/com/guru/composecookbook/ui/home/advancelists/SwipeableLists.kt
app/src/main/java/com/guru/composecookbook/ui/home/androidviews/AndroidViews.kt
app/src/main/java/com/guru/composecookbook/ui/home/customfling/FlingListActivity.kt
app/src/main/java/com/guru/composecookbook/ui/home/customfling/ListItemDivider.kt
app/src/main/java/com/guru/composecookbook/ui/home/customfling/VerticalFlingerList.kt
app/src/main/java/com/guru/composecookbook/ui/home/customfling/VerticalFlingerListItem.kt
app/src/main/java/com/guru/composecookbook/ui/home/dialogs/DialogsActivity.kt
app/src/main/java/com/guru/composecookbook/ui/home/lists/ListViewActivity.kt
app/src/main/java/com/guru/composecookbook/ui/utils/CommomComponents.kt
components/carousel/src/main/java/com/guru/composecookbook/carousel/CarouselLayout.kt
demos/youtube/src/main/java/com/guru/composecookbook/youtube/components/YoutubeChip.kt

@Gurupreet 
We've migrated the Home tab and sub-items from Material you to Material 3.

Home Tab completely migrated to Material you

---

app/src/main/java/com/guru/composecookbook/ui/home/dialogs/DialogType.kt
app/src/main/java/com/guru/composecookbook/ui/home/dialogs/DialogsActivity.kt

Added Date and Time picker in DialogsActivity.kt

---

.idea/codeStyles/Project.xml
app/src/main/java/com/guru/composecookbook/MainActivity.kt
app/src/main/java/com/guru/composecookbook/ui/animation/AnimatableSuspendingAnimations.kt
app/src/main/java/com/guru/composecookbook/ui/animation/AnimateAsStateAnimations.kt
app/src/main/java/com/guru/composecookbook/ui/animation/AnimationScreen.kt
app/src/main/java/com/guru/composecookbook/ui/animation/TransitionsAnimations.kt
app/src/main/java/com/guru/composecookbook/ui/animation/VisibilityAnimations.kt
app/src/main/java/com/guru/composecookbook/ui/demoapps/DemoUIList.kt
app/src/main/java/com/guru/composecookbook/ui/home/HomeScreen.kt
app/src/main/java/com/guru/composecookbook/ui/learnwidgets/AllButtons.kt
app/src/main/java/com/guru/composecookbook/ui/learnwidgets/AppBars.kt
app/src/main/java/com/guru/composecookbook/ui/learnwidgets/Chips.kt
app/src/main/java/com/guru/composecookbook/ui/learnwidgets/Loaders.kt
app/src/main/java/com/guru/composecookbook/ui/learnwidgets/Snackbars.kt
app/src/main/java/com/guru/composecookbook/ui/learnwidgets/SwipeButton.kt
app/src/main/java/com/guru/composecookbook/ui/learnwidgets/TextInputs.kt
app/src/main/java/com/guru/composecookbook/ui/learnwidgets/Texts.kt
app/src/main/java/com/guru/composecookbook/ui/learnwidgets/Toggles.kt
app/src/main/java/com/guru/composecookbook/ui/learnwidgets/UICards.kt
app/src/main/java/com/guru/composecookbook/ui/learnwidgets/WidgetScreen.kt
app/src/main/java/com/guru/composecookbook/ui/templates/TemplateScreen.kt
app/src/main/java/com/guru/composecookbook/ui/utils/CommomComponents.kt
components/colorpicker/src/main/java/com/guru/composecookbook/colorpicker/ColorPicker.kt
theme/src/main/java/com/guru/composecookbook/theme/MaterialTheme.kt

@Gurupreet Please have a look
- Dashboard all tabs UI compatible with Material You

Dashboard Material you compatible

---

demos/twitter/src/main/java/com/guru/composecookbook/twitter/components/icons/IconCounter.kt

Uses the latest compose animation rules to show pop-up animation when the like button is pressed.
Can be used anywhere in our UI.
Easy to Use and test.🤝
Happy Hacktobrefest✨

Added animated HeartButton

---

app/src/main/java/com/guru/composecookbook/ui/home/timer/TimerDemo.kt
app/src/main/java/com/guru/composecookbook/ui/home/timer/TimerViewAnimation.kt
app/src/main/res/drawable/ic_baseline_access_time_24.xml

TimerViewAnimation
